POST http://zh.test/oauth/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=2&client_secret=AxZF5MKdrzGqQpYqgcOpjA9gzKTdw6pxlrT26oRZ&username=miguel.vazquez%40noktos.com.mx&password=Noktos2021&scope=%2A


###
@jwt = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZjEzODFlYmYzYjRhNWJhMWFkZjIzNmNiMWM1NzNiZDFkZTU1ODM3Mzg4ZmJhOGQwYTNkNWIxMjc5M2I2MzhiMmVjMzc1YWI4MmIzNTEzMWIiLCJpYXQiOjE2MTk0ODQwMjIuODIwNTkyLCJuYmYiOjE2MTk0ODQwMjIuODIwNjA1LCJleHAiOjE2MjAwODg4MjIuNTM2NTY0LCJzdWIiOiIxIiwic2NvcGVzIjpbIioiXX0.KjIDiSKoQAwBd7fR_Pwrve38gOHGZ-Rn1SJaAcSnHFsGDaAOjiKLhyOXKvWynv4TpP3lvpqMxvLDln6zXxA8UvgFRmd7clbDbyJEPn7WbHYpPx820-TYikExpQRu07mXI4ov_qOZODOZYvdQoUqosUNGgwr3JsOWQuOuWeQfmfbyLkXWaohuUYfN2rDGSZmKg1JfKoOTTPt_6rYocKiQTzHaMJSxYQkbkl8ZNPjOrKOP3VIz1gjoLeW-AnPkW8j0LsU_-c87i3Jz-1o5fTqIQtEgxWQ_nw2u-UPIMZacWU4BczXGSN5_ZoujR1t0EspJQG6zTWwxnq-_PrjymKY_6pja_P5vD1LDL0HGt3qFgnoM8TeD66GpXl0JIJYOgIMSKAq4WOsv-kDrjVpoh9CeL8pe-A3tlpB-xy5dZOXiGc-WPVb81_3nTB5QwxtU9TwQcjPxgrOdo-pSS2KtRveQ7qbJPyyA8OGOcPPUIJum9Ieuefa9npMBML1glB4xQ9CIlOfwDgCgj8Ls9TcIbtSv0h3pIy940IX2GIM7gxsVfhwTjDgClUBwCBDsoTvbeb7tGxRu81E42Gced5qIrtmQu3okrfVpuMD_CehCS8DKPU0i4BR9IHUc037G3YizbFBoMMCqcyzkONYQFxV6rTtGxM_bMURNCxOxRmSbx0Km1oo
###
GET http://zh.test/api/user HTTP/1.1
Accept: application/json
Authorization: Bearer {{jwt}}