###
### OBTAIN A NEW ACCESS TOKEN
###
POST https://accounts.zoho.com/oauth/v2/token HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "code": "1000.160271bb31c946015088faf1e1604459.36470a778d64d098547d4efb3efe4565",
    "client_id": "1000.DM50R798IAJJF0S6HQB9WB244E6F3O",
    "client_secret": "2f120b6cab59a7277624fff45839e13f3d37202f9f",
    "redirect_uri": "http://zh.test/zoho/redirect",
    "grant_type": "authorization_code",
    "scope": "ZohoSubscriptions.fullaccess.all",
    "state": "RETRIEVE-JWT"
}


    
###
### Convert AUTHTOKEN TO OAUTH
###

POST https://accounts.zoho.com/oauth/v2/token/self/authtooauth HTTP/1.1
Content-Type: application/json

{
    "client_id": "1000.UUNIMKTDKTEXBITS0BCK4C3RJW5T1K",
    "client_secret": "80f99888162ec195a79668846d2efd73d6108868cb",
    "grant_type": "authtooauth",
    "auth_token": "1000.526273f45e57d931c78c490eaf1156c8.139d491beb1f7edd14431f2738287454",
    "soid": "ZohoSubscriptions.749264377",
    "scope": "ZohoSubscriptions.fullaccess.all"
}
